### PR TITLE
Encode Chinese/Korean/Japanese characters to avoid failure while converting a string to an URL

### PR DESCRIPTION
**Pull request by iAugux**
If a string contains Chinese/Korean/Japanese characters, it can not be converted to an URL, so the string must be encoded before converting.

For example:
```
let str = "https://example.com/测试"  // "测试": these are Chinese characters
let url = URL(string: str)   // nil

let encodedStr = "https://example.com/%E6%B5%8B%E8%AF%95"
let encodedURL = URL(string: encodedStr)    // a valid URL
```

### CODE REVIEW

**Comment by keith** [comment]
Hey @iAugux thanks for submitting this! Is it common to get a URL like this that isn't already percent escaped? That seems less than ideal! 😛

**Comment by iAugux** [comment]
@keith I agree with you! But unfortunately, there are some companies didn't realize that, like Tumblr.
I tried to converting the url without modifying `Mapper`, it works, but the code is so ugly. 

So I wonder if you can make an option to let us choose the original URL or the encoded URL, that would be great! Thanks!

**Comment by keith** [comment]
Unfortunately I'm not sure that we should add this to Mapper itself. I'm not sure that we want to impose the effect of this change to everyone, since I think that many users would be surprised if they got an invalid URL that ended up being non-nil, such as this case:

```
% swift
Welcome to Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1). Type :help for assistance.
  1> import Foundation
  2> URL(string: "hi there")
$R0: URL? = nil
  3> URL(string: "hi there".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
$R1: URL? = "hi%20there"
```

**Comment by iAugux** [comment]
@keith That's ok. I'll do it myself. Thanks for your time!

**Comment by keith** [comment]
Thanks for the contribution! Please open any issues in the future if they come up!

**Pull request closed without merging**
