### PR TITLE
Test array of raw values with unmappable element

### PR DESCRIPTION
**Pull request by lzell**

### CODE REVIEW

**Comment by lzell** [comment]
Is that the same thing? What I'm testing here is:
given an array of strings `["valid1", "valid2", "invalid"]`
mapper will map to an array of enums `[.valid1, .valid1]`

**Comment by keith** [comment]
Ah you are using that. I thought the context here was hoping that this wasn't the behavior.

**Comment by lzell** [comment]
Yeah, I wanted a test around this behavior (which is current) so that if this assumption breaks we hear about it.

I've got an array of strings coming down from the backend that map to an enum:

```
enum Foo: String {
  case one
  case two
}
```

If _already deployed_ clients with this definition of Foo start receiving a third string (say we've made a backend change and are sending down ["one", "two", "three"]), I want to ensure that the already deployed client still maps to `[.one, .two]` and _not_ `[]`.

**Comment by keith** [comment]
Yep definitely. The test you edited here does cover this case since optionalFrom is implemented as `try? from`

**Comment by lzell** [comment]
Yeah it's super close. Maybe close enough (if you think it is I'll cancel this no sweat). The only difference in setup is that the new test does not expect an optional. Implementation-wise I'm sure this doesn't make a difference, but from a caller's perspective there could be a subtle difference in behavior between asking for `thing: [Foo] = try map.from(...)` and `thing: [Foo]? = map.optionalFrom(...)`. Figured a test would make this explicit

**Comment by keith** [comment]
Yep sounds good!

**Pull request merged**
