### PR TITLE
Added throwable from method.

### PR DESCRIPTION
**Pull request by petaren**
Sometimes it is desirable to have a version that will throw instead of return nil. Maybe the naming isn't perfect and I'm open to suggestions for any changes.

### CODE REVIEW

**Comment by Reflejo** [comment]
I think the full syntax is a bit more expressive than the `fromThrowable` (which at this points it serves as syntax sugar if I got this right).

e.g.:
```swift
try Model(map: Mapper(JSON: [:]))
```
vs
```swift
Model.fromThrowable([:])
```

**Comment by keith** [comment]
After talking to @Reflejo about this I think we should do it. There are a few things we'll need to do to merge this though.

1. Come up with a slightly nicer name for this function. I wish we could reuse `from` here, but there's [an issue with that](http://www.openradar.me/radar?id=4991483920777216)
1. Make `Mapper`'s `init(JSON` `internal`. This way we can have only 1 way for consumers to create `Mappable`s from JSON, but we can still use that internally.
1. Convert the tests for these new changes
1. Fix the trailing whitespace mentioned in the lint failure: https://travis-ci.org/lyft/mapper/jobs/97270151
1. Update the README
1. Add it to the CHANGELOG as a breaking change
1. Sign our CLA https://github.com/lyft/CLA

**Comment by petaren** [comment]
@Reflejo
 I didn't think about that you could use the full syntax. 

@keith 
Sounds like a good action-list. I could get on it during the weekend.

**Comment by keith** [comment]
I realized today that we may not be able to eliminate the initializer because of this case:

```swift
struct Foo: Mappable {
    let string: String
    init(map: Mapper) throws {
        string = map.optionalFrom("string") ?? "default value"
    }

    // Another initializer for default values
    init() {
        try! self.init(map: Mapper(JSON: [:]))
    }
}
```

In our codebase we're doing this at least once or twice with model objects where we don't force any value to exist, and we want to be able to create an "empty" version without having to duplicate the default values in another initializer. In this case we _have_ to be able to use `self.init`. There might be a better way to solve this, possibly another `Mappable` protocol where the initializer doesn't throw as a first step.

**Comment by keith** [comment]
Closing this for now. Feel free to reopen!

**Pull request closed without merging**
