### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @keith! Thanks for the hard work on the Swift 3.0 branch! Any info about releasing the (at least) beta version via CocoaPods? Would love to release beta version of [Moya-ModelMapper](https://github.com/sunshinejr/Moya-ModelMapper) 🐼

**Comment by keith** [comment]
I'll fix and merge this early next week if we don't have any other issues with it.

**Comment by sunshinejr** [comment]
Thanks! 👊

**Comment by Killectro** [comment]
Love the work @keith! Any updates for the push to Cocoapods? Itching to migrate to Swift 3 🚀

**Comment by keith** [comment]
Feel free to point to this branch in the meantime. If you could integrate this branch and make sure everything is still working as expected that would be awesome! I'm currently working on migrating our project and I want to test it with our models as a sanity check before merging.

**Comment by Killectro** [comment]
Sadly we also depend @sunshinejr's Moya-ModelMapper so we can't point directly to the branch 😞

**Comment by keith** [comment]
I've pushed 5.0.0 with Swift 3 support to CocoaPods! Please open new issues for any problems you have! Thanks everyone!

**Pull request merged**
