### PR TITLE
Added watchOS target

### PR DESCRIPTION
**Pull request by Austinate**
I see only 1 problematic part here — watchOS doesn't support XCTest yet 😮

### CODE REVIEW

**Comment by keith** [comment]
Hilarious that you still can't test these frameworks. I guess we shouldn't wait for that though. We can instead make a different test to ensure the Cathage framework builds I guess.

**Comment by keith** [comment]
Thanks for doing this one too! I'll check it out ASAP

**Comment by Austinate** [comment]
Welcome! 
When you're saying about different test case — it's about test case for default target or some sort of Travis magic (not familiar with it at all, unfortunately). Sorry if question sounds a bit stupid ¯\_(ツ)_/¯

**Comment by keith** [comment]
Right now we have 4 different tests that run on each PR, currently one for each platform, and a lint build. https://github.com/lyft/mapper/blob/master/.travis.yml#L4-L7

We could add a carthage phase to this just to make sure it builds correctly. Since I'm not sure what more we can do until watchOS has XCTest support...

**Comment by keith** [comment]
While that won't stop us from breaking behavior it will at least make sure we don't add things that watchOS doesn't support (like some unsupported framework)

**Comment by keith** [comment]
I started working on the carthage test, but ran into some makefile issues. I'll probably get to it soon, it's currently here: https://github.com/lyft/mapper/compare/Austinate-master

**Comment by keith** [comment]
Thanks for doing this, I did a little more research and ended up removing all the platform specific frameworks. See https://github.com/lyft/mapper/pull/20 for the final product, including watchOS support.

**Pull request closed without merging**
