### PR TITLE
Added tvOS target

### PR DESCRIPTION
**Pull request by Austinate**
Easy as that. 
Somebody (like me) would like to use it for tvOS :)

### CODE REVIEW

**Comment by keith** [comment]
Thanks for submitting this! Let me clone it on my machine, run the tests, then merge it!

**Comment by Austinate** [comment]
Welcome! 
Sure :) 
Also i see watchOS target is missing, would you like me to create separate PR or update current one?

**Comment by keith** [comment]
If you'd like to add a watchOS target please add it in a separate PR. Your CLA PR has been merged so we're good to go there. I'm tweaking some stuff with this PR to attempt to get the tvOS tests running on Travis as well. Just to make sure we don't merge any incompatible code without knowing.

**Comment by keith** [comment]
Thanks for this! It was merged here: https://github.com/lyft/mapper/commit/3fd73112cf84e472357344add59409f1ba3d871a

**Pull request closed without merging**
